/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiyi_hcdndownloader_CupidForPlayer */

#ifndef _Included_com_qiyi_hcdndownloader_CupidForPlayer
#define _Included_com_qiyi_hcdndownloader_CupidForPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiyi_hcdndownloader_CupidForPlayer
 * Method:    GetAdPath
 * Signature: (JILjava/lang/String;I)Lcom/qiyi/hcdndownloader/PlayerGetAdPathResult;
 */
JNIEXPORT jobject JNICALL Java_com_qiyi_hcdndownloader_CupidForPlayer_GetAdPath
  (JNIEnv *, jobject, jlong, jint, jstring, jint);

/*
 * Class:     com_qiyi_hcdndownloader_CupidForPlayer
 * Method:    SetSavePathAd
 * Signature: (Ljava/lang/String;JILjava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_qiyi_hcdndownloader_CupidForPlayer_SetSavePathAd
  (JNIEnv *, jobject, jstring, jlong, jint, jstring, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
