/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiyi_hcdndownloader_HCDNDownloaderCreator */

#ifndef _Included_com_qiyi_hcdndownloader_HCDNDownloaderCreator
#define _Included_com_qiyi_hcdndownloader_HCDNDownloaderCreator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    CreateTask
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Lcom/qiyi/hcdndownloader/HCDNDownloaderTask;
 */
JNIEXPORT jobject JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_CreateTask
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    CreateTaskByUrl
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/qiyi/hcdndownloader/HCDNDownloaderTask;
 */
JNIEXPORT jobject JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_CreateTaskByUrl
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    CreateTaskWithAD
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZIIIZZIII)Lcom/qiyi/hcdndownloader/HCDNDownloaderTask;
 */
JNIEXPORT jobject JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_CreateTaskWithAD
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jboolean, jint, jint, jint, jboolean, jboolean, jint, jint, jint);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    DestroryTask
 * Signature: (Lcom/qiyi/hcdndownloader/HCDNDownloaderTask;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_DestroryTask
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    InitHCDNDownloaderCreator
 * Signature: (IIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_InitHCDNDownloaderCreator
  (JNIEnv *, jobject, jint, jint, jint, jstring, jstring, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    InitCubeCreator
 * Signature: (IIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_InitCubeCreator
  (JNIEnv *, jobject, jint, jint, jint, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    DestroyHCDNDownloaderCreator
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_DestroyHCDNDownloaderCreator
  (JNIEnv *, jobject);


/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    GetParam
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_GetParam
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    SetParam
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_SetParam
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    SetCubeParam
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_SetCubeParam
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    StartCubeNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_StartCubeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderCreator
 * Method:    StopCubeNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderCreator_StopCubeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
