/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiyi_hcdndownloader_HCDNDownloaderTask */

#ifndef _Included_com_qiyi_hcdndownloader_HCDNDownloaderTask
#define _Included_com_qiyi_hcdndownloader_HCDNDownloaderTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    Start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_Start
  (JNIEnv *, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    Stop
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_Stop
  (JNIEnv *, jobject,jint);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    RegisterTaskCallback
 * Signature: (Lcom/qiyi/hcdndownloader/IHCDNDownloaderTaskCallBack;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_RegisterTaskCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    SetAddtionalInfo
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_SetAddtionalInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    GetSpeed
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_GetSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    GetFileSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_GetFileSize
  (JNIEnv *, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    GetDownloadSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_GetDownloadSize
  (JNIEnv *, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    SetSpeedLimit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_SetSpeedLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    IsFilerExist
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_IsFilerExist
  (JNIEnv *, jobject);
  
/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    DeleteDownloaderFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_DeleteDownloaderFile
  (JNIEnv *, jobject);
  
/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    GetParam
 * Signature: (Ljava/lang/String;)Ljava/lang/String
 */
JNIEXPORT jstring JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_GetParam
  (JNIEnv *, jobject, jstring);
  
/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    SetParam
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_SetParam
  (JNIEnv *, jobject, jstring, jstring);
  
#ifdef __cplusplus
}
#endif
#endif
