/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiyi_hcdndownloader_HCDNDownloaderTask */

#ifndef _Included_com_qiyi_hcdndownloader_HCDNDownloaderTask
#define _Included_com_qiyi_hcdndownloader_HCDNDownloaderTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    StartNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_StartNative
  (JNIEnv *, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    StopNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_StopNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    RegisterTaskCallbackNative
 * Signature: (Lcom/qiyi/hcdndownloader/IHCDNDownloaderTaskCallBack;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_RegisterTaskCallbackNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    SetAddtionalInfoNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_SetAddtionalInfoNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    GetSpeedNative
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_GetSpeedNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    GetFileSizeNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_GetFileSizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    GetDownloadSizeNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_GetDownloadSizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    SetSpeedLimitNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_SetSpeedLimitNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    IsFilerExistNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_IsFilerExistNative
  (JNIEnv *, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    DeleteDownloaderFileNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_DeleteDownloaderFileNative
  (JNIEnv *, jobject);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    GetParamNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_GetParamNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_HCDNDownloaderTask
 * Method:    SetParamNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qiyi_hcdndownloader_HCDNDownloaderTask_SetParamNative
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
