/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiyi_hcdndownloader_CheckQSV */

#ifndef _Included_com_qiyi_hcdndownloader_CheckQSV
#define _Included_com_qiyi_hcdndownloader_CheckQSV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiyi_hcdndownloader_CheckQSV
 * Method:    StartCheckQSVNative
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qiyi_hcdndownloader_CheckQSV_StartCheckQSVNative
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_CheckQSV
 * Method:    StopCheckQSVNative
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qiyi_hcdndownloader_CheckQSV_StopCheckQSVNative
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_qiyi_hcdndownloader_CheckQSV
 * Method:    RegisterCheckCallbackNative
 * Signature: (Lcom/qiyi/hcdndownloader/ICubeCheckQSVCallBack;)I
 */
JNIEXPORT jint JNICALL Java_com_qiyi_hcdndownloader_CheckQSV_RegisterCheckCallbackNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
